Repository cboard-org/cboard-ai-engine, pull requests merged in 2024-03, with the labels that each got.

#11 Fix / Function parameters
  README.md
  package.json
  src/constants.ts
  src/engine.ts
  src/index.ts
Labels: bug, documentation

#15 Improve TypeScript Typings and Engine Implementation
  package-lock.json
  package.json
  src/engine.ts
  src/index.ts
Labels: enhancement, refactor

#17 Refactor processPictograms function to wait the pictonizaer response before send new request
  src/engine.ts
Labels: enhancement, refactor

#30 fix: return the exact number of pictos
  run.ts
  src/engine.ts
Labels: enhancement
